### ISSUE TITLE
初始化无法运行

### ISSUE THREAD

**Issue by yileye** [sx1989827/SBDoc#7]
[root@bogon SBDoc-1.1.9]# sudo node SBDoc/bin/www 
/data/tools/SBDoc-1.1.9/SBDoc/routes/checkUser.js:16
    let bUp=false;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/tools/SBDoc-1.1.9/SBDoc/app.js:8:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by yileye** [comment]
## cat config.json 
{
  "db":"mongodb://localhost:27017/SBDoc",
  "filePath":"/data/tools/SBDoc-1.1.9",
  "imgPath":"/data/tools/SBDoc-1.1.9/img",
  "tempPath":"/data/tools/SBDoc1.1.9/temp",
  "port":10000,
  "version":"1.1.9"
}

**Comment by sx1989827** [comment]
版本低了 建议使用readme里面的版本6.10.0

**Comment by yileye** [comment]
已解决
